<?php
namespace app\admin\model;
use heephp\model;
use heephp\relation;

class basefilter extends model
{

    public function __construct($tbname)
    {
        parent::__construct($tbname);
    }

    public function insert($data)
    {
        $data = $this->filter($data);
        return parent::insert($data); // TODO: Change the autogenerated stub
    }

    public function update($data)
    {
        $data = $this->filter($data);
        return parent::update($data); // TODO: Change the autogenerated stub
    }

    public function save($data)
    {
        $data = $this->filter($data);
        return parent::save($data); // TODO: Change the autogenerated stub
    }

    private function filter($data){
        $fs = ['title','name','body','keyword','description','remark','context'];
        foreach ($fs as $f){
            if(array_key_exists($f,$data))
                $data[$f] = replacetxt($data[$f]);
        }
        return $data;
    }

}